import 'package:share_plus/share_plus.dart';
/// 分享卡片文案（Flutter 无 Canvas 依赖时的轻量实现）
class ShareCardService {
  static Future<void> shareAsCard({
    required String text,
    required String sceneName,
    String? toneLabel,
  }) async {
    final header = 'ClearTalk · $sceneName';
    final tone = toneLabel != null ? '\n${toneLabel}' : '';
    final body = '''
━━━━━━━━━━━━━━━━
$header$tone
━━━━━━━━━━━━━━━━

$text

━━━━━━━━━━━━━━━━
Generated by ClearTalk
''';
    await Share.share(body.trim(), subject: header);
  }
}
